---
title: "Review"
---

This page collects review material for the course.

## Entry requirements

We assume you have a background in mathematics corresponding to the contents of the WASP course “Mathematics and Machine Learning”. You will need solid programming experience in a high-level language; the programming assignments will use Python. You should be comfortable with modern deep learning techniques and frameworks, for instance as taught by the WASP course “Deep Learning and GANs”. We do not assume previous knowledge of NLP.

## Linguistics

We do not expect you to have any background in linguistics, but will often use linguistic terminology. (No natural language processing without language!) The following video provides a compact, 30-minute introduction to some of the essentials of linguistics that you may encounter in the course.

[Essentials of linguistics](https://youtu.be/jOm1Mvx8DbA)

## Basic text processing

The exercises and assignments in this course require solid programming experience. In particular, you will benefit from previous experience with text processing in Python. If you need to get up to speed on this, we have a notebook that introduces some basic concepts and techniques for processing text data.

[Basic text processing](https://gitlab.liu.se/nlp/tdde09/-/blob/main/sessions/basic-text-processing/basic-text-processing.ipynb)

## PyTorch

As our deep learning framework, we will use [PyTorch](https://pytorch.org/). Many good introductions to PyTorch are available online. The notebook we provide here is focused on those concepts and techniques that you will encounter in the exercises and assignments.

[Introduction to PyTorch](Introduction_to_PyTorch.ipynb)

## Using Colab

Most of the assignments and exercises will require you to use a GPU-based machine. If you do not have easy access to such a machine at your institution, using Google's free Colab service may be an alternative. We have written some instructions describing the basics of how to work with Colab.

[Using Colab](http://www.cse.chalmers.se/~richajo/dat450/reading/using_colab.html)