---
title: "Meeting 2"
---

The second meeting will take place 16&ndash;17 May at Chalmers, Gothenburg.

## Schedule

| Time | Activity |
|------|----------|
| **Thursday** | |
| 11:30–13:00 | Lunch at [Waste](https://maps.app.goo.gl/6V9uAXxUdLLVop2Y8) |
| 13:00–14:30 | Discussion: Large language models |
| 14:30–15:00 | Fika |
| 15:00–17:00 | Exercise 2-1: Efficient fine-tuning |
| **Friday** | |
| 09:00–10:00 | Discussion: Summarization use case |
| 10:00–10:30 | Fika |
| 10:30–11:30 | Exercise 2-2: Using open LLMs |
| 11:30–12:30 | Lunch at [Waste](https://maps.app.goo.gl/6V9uAXxUdLLVop2Y8) | 
| 12:30–15:00 | Project practicalities; Introduction to Assignment 2 |
: {.striped .hover}

## Practical information

**Venue.** For the sessions, we will use the room [SB-L200](https://maps.chalmers.se/#b7834339-e8ef-4c9a-b593-b89854ccfa72), located at [Sven Hultins gata 6](https://maps.app.goo.gl/bVfwLpVusv3LoGKk7).
At the entrance, walk right and take the first staircase to SB-L200.

Lunch both days will be at [Waste](https://maps.app.goo.gl/6V9uAXxUdLLVop2Y8), Sven Hultins Plats 5.

**Public transport.** The [**Chalmers**](https://maps.app.goo.gl/sk3ygGvYDt2wcfEN8) tram and bus stop is located a short distance from the classroom and the lunch restaurant.

From the train station, you can walk a short distance to [**Brunnsparken**](https://maps.app.goo.gl/1Zi2gNZNvEWeLzHk9), from which the following two lines can be taken directly to Chalmers.

* Tram 10 (towards Guldheden)
* Bus 16 (towards Högsbohöjd)

You can use the [Västtrafik](https://www.vasttrafik.se/en/) app or [pay with a credit card](https://www.vasttrafik.se/en/Tickets/more-about-tickets/Tap-payment/) for a single ticket.