---
title: "Meeting 1"
---

The first meeting will take place 11–12 April in Linköping.

## Schedule

The meeting will start with lunch at 12:00 on Thursday, 11 April and end at 15:00 on Friday, 12 April. Here is a rough schedule:

| Time | Activity |
|------|----------|
| **Thursday** | |
| 12:00–13:00 | Lunch at [Kårallen](https://www.compass-group.se/restauranger-och-menyer/ovriga-restauranger/karallen/), Gästmatsalen |
| 13:00–13:30 | Welcome. Course logistics |
| 13:30–14:30 | Discussion: Word and document representations |
| 14:30–15:00 | Fika in [Ljusgården](https://link.mazemap.com/KTWYvTGh) |
| 15:00–17:00 | Exercise: Simple neural NLP models from scratch ([notebook](https://colab.research.google.com/drive/1wZlxgaWsJaOxMhIHmjQpjLsg0QZkQiMQ?usp=sharing)) |
| 18:30–21:00 | Dinner at [Olympia Da Vinci](http://www.olympia-davinci.se) |
| **Friday** | |
| 09:00–10:00 | Discussion: Bias in NLP models |
| 10:00–10:30 | Fika in [Ljusgården](https://link.mazemap.com/KTWYvTGh) |
| 10:30–12:00 | Exercise: Using pre-trained NLP models from Hugging Face ([notebook](https://drive.google.com/file/d/1yHH_iR4RZaDFNvN9iIfcH_Eo6yYRxaRU/view?usp=sharing)) |
| 12:00–13:00 | Lunch at [Universitetsklubben](https://www.hors.se/linkoping/17/6/universitetsklubben/) |
| 13:00–14:00 | Introduction to the project |
| 14:00–15:00 | Getting started on Assignment 1 |

: {.striped .hover}

## Practical information

**Meeting venue.** We will be at Linköping University, in [B-huset](https://link.mazemap.com/gwzVmFfP), Campus Valla. Most sessions will be in lecture hall [Nobel](https://link.mazemap.com/o7AFQD2b). For fikas we will walk over to [Ljusgården](https://link.mazemap.com/KTWYvTGh). Lunches will be in [Kårallen](https://www.compass-group.se/restauranger-och-menyer/ovriga-restauranger/karallen/) and [Universitetsklubben](https://www.hors.se/linkoping/17/6/universitetsklubben/).

**Public transport.** You can choose between two bus lines to get to B-huset from the city center using public transport ([Östgötatrafiken](https://www.ostgotatrafiken.se/)). The specified travel times include a final walk from the bus stop to the meeting room.

* Bus no. 4 to Lambohov, get off at [Nobeltorget](https://www.ostgotatrafiken.se/hallplats/nobeltorget) (25 minutes)
* Bus no. 12 to Lambohov, get off at [Universitetet](https://www.ostgotatrafiken.se/hallplats/universitetet-linkoping) or [Mästar Mattias väg](https://www.ostgotatrafiken.se/hallplats/master-mattias-vag) (20 minutes)

**Dinner.** On the first day of the meeting (11 April), we will have a joint dinner at [Olympia Da Vinci](http://www.olympia-davinci.se). You registered for the dinner when registering for the course. Address: Bielkegatan 1, 582 21 Linköping ([map](https://maps.app.goo.gl/pyQybwFJvL37HeN47))

**Hotels.** We can recommend [Scandic Frimurarhotellet](https://www.scandichotels.se/hotell/sverige/linkoping/scandic-frimurarehotellet) and [Scandic Linköping City](https://www.scandichotels.se/hotell/sverige/linkoping/scandic-linkoping-city). Both of them are located close to the city centre and train station.
